### ISSUE TITLE
fy driver fails

### ISSUE THREAD

**Issue by hb020** [hb020/sds1004x_bode#2]
As mentioned by awakephd on eevblog:

```
sudo python3 bode.py fy -udp
Initializing AWG...
AWG: fy
Port: /dev/ttyUSB0
IDN: fy
AWG initialized.
Starting AWG server...
Listening on 0.0.0.0
RPCBIND on UDP port 111
VXI-11 on TCP port 9010
Creating sockets...

Waiting for connection request...

Incoming connection from 192.168.0.201:809.
VXI-11 CREATE_LINK, SCPI command: inst0
VXI-11 DEVICE_WRITE, SCPI command: IDN-SGLT-PRI?
VXI-11 DEVICE_READ, SCPI command: None
VXI-11 DESTROY_LINK, SCPI command: None
VXI-11 moving to TCP port 9011

Waiting for connection request...

Incoming connection from 192.168.0.201:809.
VXI-11 CREATE_LINK, SCPI command: inst0
VXI-11 DEVICE_WRITE, SCPI command: IDN-SGLT-PRI?
VXI-11 DEVICE_READ, SCPI command: None
VXI-11 DESTROY_LINK, SCPI command: None
VXI-11 moving to TCP port 9012

Waiting for connection request...

Incoming connection from 192.168.0.201:809.
VXI-11 CREATE_LINK, SCPI command: inst0
VXI-11 DEVICE_WRITE, SCPI command: C1:OUTP LOAD,50;BSWV WVTP,SINE,PHSE,0,FRQ,15000,AMP,2,OFST,0;OUTP ON
C1:OUTP LOAD,50;BSWV WVTP,SINE,PHSE,0,FRQ,15000,AMP,2,OFST,0;OUTP ON
Warning: WMF00015000000000 did not produce an expected response after 2 retries
Traceback (most recent call last):
  File "/home/uwake/Software/FY6900/sds1004x_bode-master/sds1004x_bode/bode.py", line 45, in <module>
    server.start()
  File "/home/uwake/Software/FY6900/sds1004x_bode-master/sds1004x_bode/awg_server.py", line 120, in start
    self.main_loop()
  File "/home/uwake/Software/FY6900/sds1004x_bode-master/sds1004x_bode/awg_server.py", line 140, in main_loop
    self.process_lxi_requests()
  File "/home/uwake/Software/FY6900/sds1004x_bode-master/sds1004x_bode/awg_server.py", line 244, in process_lxi_requests
    self.parser.parse_scpi_command(scpi_command)
  File "/home/uwake/Software/FY6900/sds1004x_bode-master/sds1004x_bode/command_parser.py", line 49, in parse_scpi_command
    self.parse_bswv(args, channel)
  File "/home/uwake/Software/FY6900/sds1004x_bode-master/sds1004x_bode/command_parser.py", line 80, in parse_bswv
    self.awg.set_amplitude(channel, ampl)
  File "/home/uwake/Software/FY6900/sds1004x_bode-master/sds1004x_bode/awgdrivers/base_awg.py", line 42, in set_amplitude
    raise NotImplementedError()
NotImplementedError
```

**Comment by hb020** [comment]
This particular bug is repaired now, leaving the issue open until it is fully tested.

**Comment by hb020** [comment]
done
